### ISSUE TITLE
[BUG] TourAPI 데이터 내 주요 값의 부재

### ISSUE THREAD

**Issue by laigasus** [Strong-Potato/TripVote-BE#215]
## 설명

TourAPI에서 제공하는 데이터 내에 필수로 사용하는 데이터 값이 비어있는 것이 있음
- contentId
- areaCode
- sigunguCode

TourAPI 내 결함이 발견됨

## 오류 발생 재현

1. FE측에서 무한스크롤로
2. 데이터 목록을 쭈욱 가져오는데
3. 위 제시한 값이 비어있어서 
4. 양수 식별자 parseInt 수행시 `NumberFormatException` 이 발생

## 기대 결과

결함 있는 데이터는 제외하고 서빙하는 것으로 FE 담당자와 합의되었음

##  첨부 자료

TourAPI 사이트에서 부재된 데이터로 단건 조회시 사이트가 다운되는 것으로 봐서 의도한 값은 아닌 것으로 판단됨

![스크린샷 2024-01-28 001502](https://github.com/Strong-Potato/TripVote-BE/assets/26517061/5d53b1ac-d4ed-4515-9243-e54ce5ce92bd)

결함 데이터 사례

![스크린샷 2024-01-27 235106](https://github.com/Strong-Potato/TripVote-BE/assets/26517061/e2443f9f-e7a3-49f0-8eda-1a7d84f94f15)
![스크린샷 2024-01-28 001133](https://github.com/Strong-Potato/TripVote-BE/assets/26517061/edbe5ff5-9eda-42fe-ab66-4dba2599c35e)

**Comment by Dr-KoKo** [comment]
추가로 서버쪽 로그도 남겨둡니다.
![image](https://github.com/Strong-Potato/TripVote-BE/assets/97681286/056f0dd0-38a1-41c5-b970-aa28cedcd9d5)

**Comment by laigasus** [comment]
> 추가로 서버쪽 로그도 남겨둡니다. ![image](https://private-user-images.githubusercontent.com/97681286/300203921-056f0dd0-38a1-41c5-b970-aa28cedcd9d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzODI5OTQsIm5iZiI6MTcwNjM4MjY5NCwicGF0aCI6Ii85NzY4MTI4Ni8zMDAyMDM5MjEtMDU2ZjBkZDAtMzhhMS00MWM1LWI5NzAtYWEyOGNlZGNkOWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDE5MTEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZWZlYjNlMzRhNWQzOTY2NmZhM2VmNTNhZDc4MDMzYWQ2YzAwNDc4NDY1MmQ5ZjkwODM1ZDk2Nzk1MTVkZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RAC44uOmBOBlZIfuNj8k21e0IEUabV9eokaurFFxqeg)

@happymink 담당자분 확인 부탁드립니다!

**Comment by Dr-KoKo** [comment]
> > 추가로 서버쪽 로그도 남겨둡니다. ![image](https://private-user-images.githubusercontent.com/97681286/300203921-056f0dd0-38a1-41c5-b970-aa28cedcd9d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzODI5OTQsIm5iZiI6MTcwNjM4MjY5NCwicGF0aCI6Ii85NzY4MTI4Ni8zMDAyMDM5MjEtMDU2ZjBkZDAtMzhhMS00MWM1LWI5NzAtYWEyOGNlZGNkOWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDE5MTEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZWZlYjNlMzRhNWQzOTY2NmZhM2VmNTNhZDc4MDMzYWQ2YzAwNDc4NDY1MmQ5ZjkwODM1ZDk2Nzk1MTVkZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RAC44uOmBOBlZIfuNj8k21e0IEUabV9eokaurFFxqeg)
> 
> @happymink 담당자분 확인 부탁드립니다!

다른 이슈인가 보군요. 새로운 이슈로 이관하겠습니다.
