### ISSUE TITLE
[BUG] PlaceController의 sendPlaceInfo 호출시 에러 발생

### ISSUE THREAD

**Issue by Dr-KoKo** [Strong-Potato/TripVote-BE#229]
## 설명

PlaceController의 sendPlaceInfo 호출시 `UnsupportedOperationException` 발생
1. 원인 파악 및 해결
2. ErrorHandling 추가
을 하면 좋을 것 같습니다.

## 오류 발생 재현

서버 로그를 확인한 것이기 때문에 정확한 발생 경위는 알기 힘든 것 같습니다.
추후 ErrorHandling하면서 GlobalExceptionHandler에서 요청 url을 로그로 찍는 과정이 추가되면 좋을 것 같습니다.

## 기대 결과

가능하면 `UnsupportedOperationException`의 발생 가능성 자체를 해결하고,
곤란한 경우 `ErrorHandling`을 하여서 로그를 찍고, Client에 예외 발생의 경위를 알려주면 좋을 것 같습니다.

##  첨부 자료

![image](https://github.com/Strong-Potato/TripVote-BE/assets/97681286/5e468872-4447-4969-ac68-066ff4633709)

**Comment by laigasus** [comment]
@Dr-KoKo 에러 핸들링 Scope 에 대한 논의가 필요합니다.
`@Retry` 의 구현으로 인해 불가피하게 openapi 모듈 내 throw 하는 유일한 클래스 입니다.
저게 throw를 하지 않으면 재시도 요청을 하지 않습니다.

프로젝트 구조 조정 후 반영할 수 있어 보입니다.

**Comment by Dr-KoKo** [comment]
네 어떤 상황인지 이해 했습니다. 추후 구조조정할 때 논의사항으로 부치도록 하겠습니다

**Comment by laigasus** [comment]
@Dr-KoKo 일단 저 위의 오류는 관광공사 TourAPI 자체 내부 서버 장애입니다! 
```yaml
APPLICATION_ERROR:
  title: Application Error
  detail: Tour API 서버 어플리케이션 에러입니다.
```
