### ISSUE TITLE
[BUG] 멀티 모듈 구조 변경 이후 CI test 가 수행되지 않음

### ISSUE THREAD

**Issue by laigasus** [Strong-Potato/TripVote-BE#51]
## 설명

제.곧.내

------

## 오류 발생 재현

이렇게 했더니 다음과 같은 오류가 발생했습니다

1. 멀티모듈 반영 이후 https://github.com/Strong-Potato/TripVote-BE/pull/16
2. 어느 Feat 브랜치에서 테스트 코드가 작성된 커밋을 봐서  https://github.com/Strong-Potato/TripVote-BE/pull/46/commits/194e1c6a422e54ece55a0d805024bdc25d874de2
3. 해당 PR을 봤는데 https://github.com/Strong-Potato/TripVote-BE/pull/46
4. CI  test  workflow 가 동작하지 않았습니다

------

## 기대 결과

![image](https://github.com/Strong-Potato/TripVote-BE/assets/26517061/c105c5b6-d29e-47b8-a689-43e1c68f17ac)

-----

## 나의 환경

외부적 환경으로 인해 문제가 발생한 것 같다면 기재해줍니다

**Desktop**

 - OS: windows 11
 - IDE: Intellij
 - Browser: Chrome

**Comment by laigasus** [comment]
멀티모듈 기능때문의 오류는 아닌 것으로 확인되었습니다. 
저 시점에서의 단체 작업 수행 과정에서 문제가 발생했던 것으로 보입니다. 

github action 이 비활성화되어 있었음. 지금 변경됨

![image](https://github.com/Strong-Potato/TripVote-BE/assets/26517061/126825f3-6ce0-40c8-8ad5-8105b0a5866e)

**Comment by Dr-KoKo** [comment]
Organization의 Action policy가 바뀌어 있는 것으로 확인했습니다. 저희 레포지토리에도 권한을 부여하여서 이제 action은 잘 돌아가는 것으로 확인했습니다.

**Comment by laigasus** [comment]
최근 pr 에서 동작하는 것 확인했습니다.
https://github.com/Strong-Potato/TripVote-BE/pull/54
