### ISSUE TITLE
[BUG] `@SpringBootTest` 시 JpaQueryFactory Bean이 2개 이상 발견되는 현상.

### ISSUE THREAD

**Issue by Nine-JH** [Strong-Potato/TripVote-BE#66]
## 설명

@SpringBootTest 시 JpaQueryFactory Bean이 2개 이상 발견되는 현상

## 오류 발생 재현

빌드 전 테스트 수행 시 오류 발생 

1. Gradle > Validator > Test 실행 
2. 해당 Test 코드에서 테스트 실행 

## 기대 결과

테스트 수행 시 실패없이 정상 작동한다.

**Comment by NoJaeHyuk** [comment]
PR #67 에 대한 내용입니다.
